name: "Dependabot Automerge - Action"
on:
  pull_request:
jobs:
  worker:
    runs-on: ubuntu-latest
    
  if: >
    github.event_name == 'pull_request' &&
    github.event.pull_request.draft == false && (
      github.event.action == 'opened' ||
      github.event.action == 'reopened' ||
      github.event.action == 'synchronize'
    ) && (
      github.actor == 'dependabot[bot]'
    )
        
    steps:
      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
